labels: ["needs-confirmation"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please read through the [rules](https://github.com/syntactical-code/maptactical/discussions/1) and search for existing reports before creating a new one.
  
  - type: markdown
    attributes:
      value: "# Problem Details"
      
  - type: textarea
    attributes:
      label: Description
      description: |
        Provide a detailed description of the problem you encountered.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe what you expected to occur.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Platforms
      description: |
        Which platforms did this problem occur on?
      options:
        - label: macOS
        - label: iOS (iPad)
        - label: iOS (iPhone)
    validations:
      required: true

  - type: input
    attributes:
      label: OS Version
      description: |
        Which OS versions did this problem occur on?
      placeholder: e.g. macOS Sequoia 15.5, iOS 18.5
    validations:
      required: true
 
  - type: checkboxes
    attributes:
      label: "Acknowledgement"
      options:
        - label: I have reviewed the existing Problem reports and confirm that this is not a previously reported issue.
          required: true
